"""Provider-independent command, policy, result, event, and audit boundary."""

from .audit import AuditStage, CommandAuditRecord

from .audited_pipeline import (
    AuditedCommandPipeline,
    AuditedCommandPipelineResult,
    AuditIntegrationStatus,
    EventPublicationDisposition,
    ProjectionDisposition,
)

from .automation import (
    ApprovalOutcome,
    AutomationMode,
    AutomationPolicy,
    CapabilityAutomationRule,
    GateDisposition,
    GateDispositionStatus,
    GateReasonCode,
    HumanApprovalDecision,
    PolicyDecision,
    PolicyReasonCode,
    resolve_automation_gate,
)

from .command import CommandProvenance, CommandSource, GameCommand
from .combat_domain import (
    AttackDefinition,
    CombatantDefinition,
    CombatantRole,
    ControlledCombatDefinition,
    DamageDiceSpecification,
    InitialCombatSeed,
    controlled_combat_definition,
    initial_combat_seed,
)
from .controlled_round import (
    CONTROLLED_ROUND_COMMAND,
    CONTROLLED_ROUND_EVENT,
    CONTROLLED_ROUND_SCHEMA_VERSION,
    NO_GOBLIN_BEHAVIOR_REASON,
    ControlledRoundResolution,
    ControlledRoundStatus,
    InitiativeEntry,
    initiative_order,
    reduce_controlled_round,
    resolve_controlled_round,
    validate_controlled_round_payload,
)
from .durable_journal import (
    DurableEventJournalAppender,
    DurableJournalBinding,
    DurableJournalHealth,
    DurableJournalHealthReason,
    DurableJournalHealthStatus,
    DurablePublicationResult,
    DurablePublicationStatus,
)
from .dice import (
    AutomaticFaceSource,
    DiceResolutionResult,
    DiceResolutionStatus,
    DiceRoll,
    DiceRollMode,
    DiceRollProvenance,
    DiceRollRequest,
    SequenceFaceSource,
    SystemRandomFaceSource,
    resolve_dice_roll,
)
from .game_engine import CommandHandler, GameEngine
from .game_event import GameEvent
from .event_journal_store import (
    EVENT_JOURNAL_STORAGE_FORMAT,
    EVENT_JOURNAL_STORAGE_SCHEMA_VERSION,
    EventJournalStore,
    EventJournalStoreResult,
    EventJournalStoreStatus,
)
from .journals import (
    CommandAuditJournal,
    CommandAuditJournalEntry,
    GameEventJournal,
    GameEventJournalEntry,
)
from .policy_gated_dispatcher import (
    PolicyGatedCommandDispatcher,
    PolicyGatedDispatchResult,
    PolicyGatedDispatchStatus,
)
from .result import GameResult, GameResultStatus
from .startup_hydration import (
    HydratedDurableRuntime,
    StartupHydrationResult,
    StartupHydrationStatus,
    hydrate_durable_runtime,
)
from .world_state import (
    ReducerRegistration,
    WorldState,
    WorldStateProjectionResult,
    WorldStateProjectionStatus,
    WorldStateProjector,
    WorldStateReducer,
)
from .world_state_holder import (
    ProjectionReasonCode,
    WorldStateHealth,
    WorldStateHolder,
    WorldStateSynchronizationStatus,
)
from .world_state_recovery import (
    WorldStateRecoveryResult,
    WorldStateRecoveryStatus,
    WorldStateRecoveryStrategy,
)

__all__ = [
    "ApprovalOutcome",
    "AuditedCommandPipeline",
    "AuditedCommandPipelineResult",
    "AuditIntegrationStatus",
    "AuditStage",
    "AutomationMode",
    "AutomationPolicy",
    "CapabilityAutomationRule",
    "AttackDefinition",
    "CombatantDefinition",
    "CombatantRole",
    "CommandHandler",
    "CommandAuditJournal",
    "CommandAuditJournalEntry",
    "CommandAuditRecord",
    "CommandProvenance",
    "CommandSource",
    "CONTROLLED_ROUND_COMMAND",
    "CONTROLLED_ROUND_EVENT",
    "CONTROLLED_ROUND_SCHEMA_VERSION",
    "ControlledCombatDefinition",
    "ControlledRoundResolution",
    "ControlledRoundStatus",
    "DurableEventJournalAppender",
    "DurableJournalBinding",
    "DurableJournalHealth",
    "DurableJournalHealthReason",
    "DurableJournalHealthStatus",
    "DurablePublicationResult",
    "DurablePublicationStatus",
    "DamageDiceSpecification",
    "AutomaticFaceSource",
    "DiceResolutionResult",
    "DiceResolutionStatus",
    "DiceRoll",
    "DiceRollMode",
    "DiceRollProvenance",
    "DiceRollRequest",
    "EventPublicationDisposition",
    "EVENT_JOURNAL_STORAGE_FORMAT",
    "EVENT_JOURNAL_STORAGE_SCHEMA_VERSION",
    "EventJournalStore",
    "EventJournalStoreResult",
    "EventJournalStoreStatus",
    "GameCommand",
    "GameEngine",
    "GameEvent",
    "GameEventJournal",
    "GameEventJournalEntry",
    "GameResult",
    "GameResultStatus",
    "GateDisposition",
    "GateDispositionStatus",
    "GateReasonCode",
    "HumanApprovalDecision",
    "HydratedDurableRuntime",
    "InitialCombatSeed",
    "InitiativeEntry",
    "NO_GOBLIN_BEHAVIOR_REASON",
    "PolicyDecision",
    "PolicyGatedCommandDispatcher",
    "PolicyGatedDispatchResult",
    "PolicyGatedDispatchStatus",
    "PolicyReasonCode",
    "ProjectionDisposition",
    "ProjectionReasonCode",
    "ReducerRegistration",
    "StartupHydrationResult",
    "StartupHydrationStatus",
    "SequenceFaceSource",
    "SystemRandomFaceSource",
    "WorldState",
    "WorldStateHealth",
    "WorldStateHolder",
    "WorldStateProjectionResult",
    "WorldStateProjectionStatus",
    "WorldStateProjector",
    "WorldStateRecoveryResult",
    "WorldStateRecoveryStatus",
    "WorldStateRecoveryStrategy",
    "WorldStateReducer",
    "WorldStateSynchronizationStatus",
    "hydrate_durable_runtime",
    "controlled_combat_definition",
    "initial_combat_seed",
    "initiative_order",
    "reduce_controlled_round",
    "resolve_dice_roll",
    "resolve_controlled_round",
    "resolve_automation_gate",
    "validate_controlled_round_payload",
]
